<?xml version="1.0"?>
<doc>
    <assembly>
        <name>OrchidRevit</name>
    </assembly>
    <members>
        <member name="T:Orchid.Revit.Applications.Sigma">
            <summary>
            Sigma methods
            </summary>
        </member>
        <member name="M:Orchid.Revit.Applications.Sigma.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Applications.Sigma.Component(System.Collections.IList,System.Collections.Generic.List{Revit.Elements.Element},System.String,System.Collections.Generic.List{System.Double},System.String,System.Double,System.Boolean)">
            <summary>
            Create Sigma Estimate component data
            </summary>
            <param name="componentTree">List containing the structure as strings {"number","text"}\nAt least one 'level' is needed!</param>
            <param name="element">Element(s)</param>
            <param name="code">Element identifier for Sigma</param>
            <param name="quantity">Quantity as numeric value</param>
            <param name="sigmaUnit">Unit identifier for Sigma</param>
            <param name="sigmaRegulation">Regulation for the Sigma Component</param>
            <param name="instance">Component as instances or summarized/nTrue select Data to be Instances, False select Data to be summarized</param>
            <returns name="component">Component</returns>
        </member>
        <member name="T:Orchid.Revit.Core.Document">
            <summary>
            Document methods
            </summary>
        </member>
        <member name="M:Orchid.Revit.Core.Document.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="P:Orchid.Revit.Core.Document.Current">
            <summary>
            Get current document
            </summary>
            <returns name="Document">Autodesk.Revit.DB.Document</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.ActiveView(Autodesk.Revit.DB.Document)">
            <summary>
            Get the active view in document
            </summary>
            <returns name="View">ActiveView</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.OpenView(Revit.Elements.Element)">
            <summary>
            Open view in the active document
            </summary>
            <param name="view">View to open</param>
            <returns name="View">New active view</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.Name(Autodesk.Revit.DB.Document)">
            <summary>
            Get the current document name
            </summary>
            <param name="document">The name of the document</param>
            <returns name="string">string</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.BackgroundOpen(System.String)">
            <summary>
            Open documents in background
            </summary>
            <param name="file">File (path) to open in the background</param>
            <returns name="Document">Autodesk.Revit.DB.Document</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.Save(Autodesk.Revit.DB.Document)">
            <summary>
            Save document
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <returns name="Document">Autodesk.Revit.DB.Document</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.SaveAs(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            SaveAs document
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <param name="name">Name for the document incl. path</param>
            <returns name="Document">Autodesk.Revit.DB.Document</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.Close(Autodesk.Revit.DB.Document,System.Boolean)">
            <summary>
            Close document
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <param name="save">Save opened document?</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.ImportImage(System.String)">
            <summary>
            Import Image into document
            </summary>
            <param name="path">Image path including file name and extension</param>
            <returns name="ImageType">ImageType</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.Info(Autodesk.Revit.DB.Document)">
            <summary>
            Get document info
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <returns name="info">Document info</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.ContainCategory(System.Collections.IList)">
            <summary>
            Does document contain category?
            </summary>
            <param name="category">Category to validate is contained in the document</param>
            <returns name="bool">List of booleans</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.ContainType(System.Collections.IList)">
            <summary>
            Does document contain type?
            </summary>
            <param name="type">Type to validate is contained in the document</param>
            <returns name="bool">List of booleans</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Document.Purge(Autodesk.Revit.DB.Document,System.Boolean)">
            <summary>
            Purge document. Set "completely" to true for including materials and assets!
            Please note "completely" purges also materials and materials assets that are 
            used in "peripheral" elements and settings. Among this is included materials/assets 
            bound to imported model elements, and materials/assets in settings like "Site" etc.
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <param name="completely">Includes purging materials and assets</param>
        </member>
        <member name="T:Orchid.Revit.Core.PostCommand">
            <summary>
            PostCommand methods
            </summary>
        </member>
        <member name="M:Orchid.Revit.Core.PostCommand.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Core.PostCommand.Purge(System.Boolean)">
            <summary>
            Purge document by Post Command.
            Post commands can only take the current document to be run once. Re-run the
            graph to re-activate the post command. To get back the "Purge" window inside
            Revit, set the "activate" value to "false" and re-run the graph once more!
            </summary>
            <param name="activate">Set to true to activate (and false to deactivate)</param>
        </member>
        <member name="T:Orchid.Revit.Core.Print">
            <summary>
            Print methods for core processes
            </summary>
        </member>
        <member name="M:Orchid.Revit.Core.Print.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Core.Print.ByView(System.String,System.Boolean,System.Boolean,System.Collections.Generic.List{System.String},System.String,System.Collections.Generic.List{Revit.Elements.Element},System.Object)">
            <summary>
            Print by view. --> Please note: If combined into one file is changed
            in this session, then the dynamo graph needs to be reloaded!
            </summary>
            <param name="printer">Printer name as string. If value is not set is default printer selected</param>
            <param name="combine">Combine into one file (Print to file must be set to true).</param>
            <param name="file">Print to file as boolean</param>
            <param name="filePath">Give a valid path and filename for the print output. If value is not set is the user asked later!</param>
            <param name="printRange">Print range as string</param>
            <param name="view">View to print as Revit Element (default: Active View)</param>
            <param name="printSetting">Printer setting as string or Revit Element</param>
        </member>
        <member name="M:Orchid.Revit.Core.Print.ByViewSheetSet(System.String,System.Boolean,System.Boolean,System.Collections.Generic.List{System.String},Revit.Elements.Element,System.Object)">
            <summary>
            Print by view sheet set. --> Please note: If combined into one file is changed
            in this session, then the dynamo graph needs to be reloaded!
            </summary>
            <param name="printer">Printer name as string. If value is not set is default printer selected</param>
            <param name="combine">Combine into one file (Print to file must be set to true).</param>
            <param name="file">Print to file as boolean</param>
            <param name="filePath">Give a valid path and filename for the print output. If value is not set is the user asked later!</param>
            <param name="viewSheetSet">ViewSheetSet to print as Revit Element</param>
            <param name="printSetting">Printer setting as string or Revit Element</param>
        </member>
        <member name="M:Orchid.Revit.Core.Print.CreateSetting(System.String,System.String,System.String,System.String,System.String,System.String,System.Double[],System.String,System.Int32)">
            <summary>
            Set print setting 
            </summary>
            <param name="printer">Printer name as string. If value is not set is default printer selected</param>
            <param name="name">name to create for the print setting</param>
            <param name="paperZize">Paper size as string. If value is not set is default paper size selected</param>
            <param name="pageOrientation">Page orientation as string.</param>
            <param name="paperPlacement">Paper placement</param>
            <param name="marginType">Print margin type</param>
            <param name="margin">Print margin value as double</param>
            <param name="zoomType">Zoom type as string</param>
            <param name="zoom">Zoom value as integer</param>       
            <returns name="PrintSetting">PrintSetting</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Print.ChangeSetting(System.String,System.Object,System.String,System.String,System.String,System.String,System.Double[],System.String,System.Int32)">
            <summary>
            Change print setting 
            </summary>
            <param name="printer">Printer name as string. If value is not set is default printer selected</param>
            <param name="printSetting">printer setting as string or Revit Element</param>
            <param name="paperZize">Paper size as string. If value is not set is default paper size selected</param>
            <param name="pageOrientation">Page orientation as string.</param>
            <param name="paperPlacement">Paper placement</param>
            <param name="marginType">Print margin type</param>
            <param name="margin">Print margin value as double</param>
            <param name="zoomType">Zoom type as string</param>
            <param name="zoom">Zoom value as integer</param>       
            <returns name="PrintSetting">PrintSetting</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Print.DeleteSetting(System.Object)">
            <summary>
            Delete print setting
            </summary>
            <param name="printSetting">printer setting as string or Revit Element</param>
        </member>
        <member name="M:Orchid.Revit.Core.Print.SetOptions(System.Object,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.String,System.String,System.String)">
            <summary>
            Set printer options
            </summary>
            <param name="printSetting">printer setting as string or Revit Element</param>
            <param name="viewLinksinBlue">View links in blue (Color prints only)</param>
            <param name="hideReforWorkPlanes">Hide ref/work planes</param>
            <param name="hideUnreferencedViewTags">Hide unreferenced view tags</param>
            <param name="maskCoincidentLines">Region edges mask coincident lines</param>
            <param name="hideScopeBoxes">Hide scope boxes</param>
            <param name="hideCropBoundaries">Hide crop boundaries</param>
            <param name="replaceHalftoneWithThinLines">Replace halftone with thin lines</param>
            <param name="hiddenLineViews">Hidden line views: Remove lines using vector or raster</param>
            <param name="rasterQuality">Appearance: Raster quality</param>
            <param name="colorDepth">Appearance: Colors</param>
            <returns name="PrintSetting">PrintSetting</returns>
        </member>
        <member name="T:Orchid.Revit.Core.ViewSheetSet">
            <summary>
            View methods for core processes
            </summary>
        </member>
        <member name="M:Orchid.Revit.Core.ViewSheetSet.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Core.ViewSheetSet.Create(System.Collections.Generic.IList{Revit.Elements.Element},System.String)">
            <summary>
            Create ViewSheetSet
            </summary>
            <param name="view">View as Revit Element</param>
            <param name="name">Name for the ViewSheetSet</param>
            <returns name="ViewSheetSet">ViewSheetSet</returns>
        </member>
        <member name="M:Orchid.Revit.Core.ViewSheetSet.Change(System.Collections.Generic.IList{Revit.Elements.Element},System.Object)">
            <summary>
            Change ViewSheetSet
            </summary>
            <param name="view">View as Revit Element</param>
            <param name="viewSheetSet">ViewSheetSet as string or Revit Element</param>
            <returns name="ViewSheetSet">ViewSheetSet</returns>
        </member>
        <member name="M:Orchid.Revit.Core.ViewSheetSet.GetView(System.Object)">
            <summary>
            Get View from ViewSheetSet
            </summary>
            <param name="viewSheetSet">ViewSheetSet as string or Revit Element</param>
            <returns name="View">View</returns>
        </member>
        <member name="M:Orchid.Revit.Core.ViewSheetSet.Delete(System.Object)">
            <summary>
            Delete ViewSheetSet
            </summary>
            <param name="viewSheetSet">ViewSheetSet as string or Revit Element</param>
        </member>
        <member name="T:Orchid.Revit.Core.File">
            <summary>
            File methods for core processes
            </summary>
        </member>
        <member name="M:Orchid.Revit.Core.File.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Core.File.Info(System.Collections.Generic.IList{System.String})">
            <summary>
            Get file(s) info
            </summary>
            <param name="file">File(s), incl. path</param>
            <returns name="info">File(s) info</returns>
        </member>
        <member name="M:Orchid.Revit.Core.File.NewProject(System.Collections.Generic.IList{System.String},System.Collections.Generic.IList{System.String})">
            <summary>
            Create new project by name
            </summary>
            <param name="file">File(s), must be new project file name(s) incl. path</param>
            <param name="template">Template(s) incl. path</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.Core.File.SaveFamily(System.String,System.Collections.Generic.IList{Revit.Elements.Family},System.Boolean,System.Boolean)">
            <summary>
            Save family by name
            </summary>
            <param name="path">Path to save files(s)</param>
            <param name="family">Family to be saved</param>
            <param name="subfolder">Create subfolder by category?</param>
            <param name="overwrite">Overwrite existing families?</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.Core.File.LoadFamily(System.Collections.Generic.IList{System.String})">
            <summary>
            Load family by file name, same core process as FamilyDocument.LoadFamily
            </summary>
            <param name="family">Path to the family file(s)</param>
            <returns name="Family">Family</returns>
        </member>
        <member name="M:Orchid.Revit.Core.File.LoadFamily(System.Collections.Generic.IList{System.String},System.Collections.Generic.IList{System.String})">
            <summary>
            Open document and load family by path, existing families will be overwritten,
            and families is upgraded if needed. Documents will be saved and closed.
            </summary>
            <param name="document">Path to the documents file(s)</param>
            <param name="family">Path to the family file(s)</param>
            <returns name="Family">Family</returns>
        </member>
        <member name="T:Orchid.Revit.Core.Object">
            <summary>
            Object methods
            </summary>
        </member>
        <member name="M:Orchid.Revit.Core.Object.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Core.Object.ToRevitType(Revit.Elements.Element)">
            <summary>
            Convert Dynamo elements to Autodesk Revit elements
            </summary>
            <param name="element">Revit.Elements.Element</param>
            <returns name="Element">Autodesk.Revit.DB.Element</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Object.ToDynamoType(Autodesk.Revit.DB.Element)">
            <summary>
            Convert Autodesk Revit elements to Dynamo elements
            </summary>
            <param name="element">Autodesk.Revit.DB.Element</param>
            <returns name="Element">Revit.Elements.Element</returns>
        </member>
        <member name="T:Orchid.Revit.Core.Parameter">
            <summary>
            Methods for parameters
            </summary>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.AddProjectParameter(System.Collections.Generic.IList{System.String},System.String,System.String,System.Boolean,System.Collections.Generic.IList{Revit.Elements.Category})">
            <summary>
            Add (create) project parameter by name. If the parameter exists in the project is the category binding being updated.
            </summary>
            <param name="parameterName">The name of the parameter to add</param>
            <param name="type">Parameter Type</param>
            <param name="group">Parameter Group</param>
            <param name="instance">Is instance parameter, otherwise it's a type parameter</param>
            <param name="category">Category(ies) the parameter applies to, If no category is supplied, all possible categories are selected</param>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.AddSharedParameter(System.Collections.Generic.IList{System.String},System.String,System.String,System.String,System.Boolean,System.Collections.Generic.IList{Revit.Elements.Category})">
            <summary>
            Add (create) shared parameter by name in the project. If the parameter exists in the project is the category binding being updated.
            </summary>
            <param name="parameterName">The name of the parameter to add</param>
            <param name="groupName">Group of the parameter for shared parameters</param>
            <param name="type">Parameter Type</param>
            <param name="group">Parameter Group</param>
            <param name="instance">Is instance parameter, otherwise it's a type parameter</param>
            <param name="category">Category(ies) the parameter applies to, If no category is supplied, all possible categories are selected</param>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.AddIfcParameters(System.Collections.Generic.IList{Autodesk.Revit.DB.Document})">
            <summary>
            Add basic IFC parameters in the project (IfcExportAs, IfcExportType, IfcDescription, IFC CAD Layer)
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.ProjectParameters(Autodesk.Revit.DB.Document)">
            <summary>
            Get all project parameters in the document
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <returns name="parameter">List of parameters</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.GlobalParameters(Autodesk.Revit.DB.Document)">
            <summary>
            Get all global parameters in the document
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <returns name="parameter">List of parameters</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.SharedParameters(Autodesk.Revit.DB.Document)">
            <summary>
            Get all shared parameters in the document
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <returns name="parameter">List of parameters</returns>
            <returns name="guid">List of guids</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.ChangeCategory(System.Collections.Generic.IList{System.String},System.Boolean,System.Collections.Generic.IList{Revit.Elements.Category})">
            <summary>
            Change category binding for parameter by name in the project
            </summary>
            <param name="parameterName">The name of the parameter to change</param>
            <param name="instance">Is instance parameter, otherwise it's a type parameter</param>
            <param name="category">Category(ies) to change the parameter binding to</param>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.Delete(System.Collections.Generic.IList{System.String})">
            <summary>
            Delete parameter by name in the project
            </summary>
            <param name="parameterName">The name of the parameter to delete</param>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.Associate(Revit.Elements.Element,System.String,System.Object)">
            <summary>
            Associate element parameter to global parameter
            </summary>
            <param name="element">Element as string or Revit.Elements.Element</param>
            <param name="parameterName">The name of the parameter</param>
            <param name="globalParameter">The name of the global parameter</param>
            <returns name="Element">Revit.Elements.Element</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.HasAssociated(Revit.Elements.Element,System.String)">
            <summary>
            Verify if parameter has associated global parameter
            </summary>
            <param name="element">Element as string or Revit.Elements.Element</param>
            <param name="parameterName">The name of the parameter</param>
            <returns name="bool">Boolean value</returns>
        </member>
        <member name="M:Orchid.Revit.Core.Parameter.GetAssociated(Revit.Elements.Element,System.String)">
            <summary>
            Get associated global parameter
            </summary>
            <param name="element">Element as string or Revit.Elements.Element</param>
            <param name="parameterName">The name of the parameter</param>
            <returns name="Parameter">Parameter</returns>
        </member>
        <member name="T:Orchid.Revit.Core.SharedParameter">
            <summary>
            Methods for parameters
            </summary>
        </member>
        <member name="M:Orchid.Revit.Core.SharedParameter.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Core.SharedParameter.SetFile(System.String)">
            <summary>
            Set the shared parameter file
            </summary>
            <param name="file">The "new" shared parameter file, incl. path</param>
            <returns name="file">The previously loaded shared parameter file</returns>
        </member>
        <member name="M:Orchid.Revit.Core.SharedParameter.GroupByType(System.String)">
            <summary>
            Get the shared parameter grouped by type
            </summary>
            <param name="file">The shared parameter file, incl. path</param>
            <returns name="parameter">List of parameters</returns>
            <returns name="guid">List of guids</returns>
            <returns name="groupName">List of group names</returns>
            <returns name="type">List of types</returns>
        </member>
        <member name="M:Orchid.Revit.Core.SharedParameter.GroupByGroupName(System.String)">
            <summary>
            Get the shared parameter grouped by group name
            </summary>
            <param name="file">The shared parameter file, incl. path</param>
            <returns name="parameter">List of parameters</returns>
            <returns name="guid">List of guids</returns>
            <returns name="groupName">List of group names</returns>
            <returns name="type">List of types</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.Category">
            <summary>
            Methods for categories
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.Category.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.Category.BuiltInCategory">
            <summary>
            Get all built in categories
            </summary>
            <returns name="Category">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Category.ByCategoryType(System.String)">
            <summary>
            Get all categories by category type
            </summary>
            <param name="categoryType">CategoryType</param>
            <returns name="Category">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Category.InDocument(Autodesk.Revit.DB.Document)">
            <summary>
            Get all categories in document
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <returns name="Category">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Category.CategoryType(System.Object)">
            <summary>
            Get the category type
            </summary>
            <param name="category">Category</param>
            <returns name="CategoryType">CategoryType</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.ElementType">
            <summary>
            Methods for elements
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.ElementType.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.ElementType.Name(Revit.Elements.Element)">
            <summary>
            Get element type name
            </summary>
            <param name="elementType">Revit.Elements.Element</param>
            <returns name="string">Name as string</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.ElementType.FamilyName(Revit.Elements.Element)">
            <summary>
            Get element type family name
            </summary>
            <param name="elementType">Revit.Elements.Element</param>
            <returns name="string">Family name as string</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.Material">
            <summary>
            Methods for materials
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.Material.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.Material.SumByElement(System.Collections.IList)">
            <summary>
            Material sum by element, return values in SI unit (m2/m3)
            </summary>
            <param name="element">List of element</param>
            <returns name="Material">List of material</returns>
            <returns name="area">List of area</returns>
            <returns name="volumne">List of volumne</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Material.Density(System.Collections.IList)">
            <summary>
            Get material asset as physical and thermal density in SI unit (kg/m3)
            </summary>
            <param name="material">List of material</param>
            <returns name="physical">List of physical density</returns>
            <returns name="thermal">List of thermal density</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.Selection">
            <summary>
            Methods for selecting elements
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.Selection.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.Selection.ElementHasMaterial(System.Collections.Generic.IList{Autodesk.Revit.DB.Document})">
            <summary>
            Get elements that has material quantities in document, return element grouped by category.
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <returns name="Element">Element</returns>
            <returns name="Category">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Selection.ElementByCategory(System.Collections.Generic.IList{Autodesk.Revit.DB.Document},System.Collections.IList)">
            <summary>
             Get all elements by category in document, return element grouped by category.
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <param name="category">Category</param>
            <returns name="Element">Element</returns>
            <returns name="Category">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Selection.ElementByCategoryType(System.Collections.Generic.IList{Autodesk.Revit.DB.Document},System.Collections.Generic.IList{System.String})">
            <summary>
            Get all elements by category in document, return element grouped by category and category type.
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <param name="categoryType">CategoryType</param>
            <returns name="Element">Element</returns>
            <returns name="Category">Category</returns>
            <returns name="CategoryType">CategoryType</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Selection.ElementByFamily(Revit.Elements.Family)">
            <summary>
            Get all elements of the specified family from the model.
            </summary>
            <param name="family">The Family</param>
            <returns name="Element">The list of elements matching the query.</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.Family">
            <summary>
            Family methods for elements
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.Family.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.Family.All">
            <summary>
            Get all family in current document
            </summary>
            <returns name="Family">Family</returns>
            <returns name="Category">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Family.ByCategory(System.Object)">
            <summary>
            Get all family by category in list of documents
            </summary>
            <param name="category">Category as string or Category type</param>
            <returns name="Family">Family</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Family.FamilyDocument(System.Collections.IList)">
            <summary>
            Open family document by family 
            </summary>
            <param name="family">Family</param>
            <returns name="Document">Autodesk.Revit.DB.Document</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Family.HasAssociated(Revit.Elements.Family)">
            <summary>
            Verify if family has associated elements
            </summary>
            <param name="family">Family</param>
            <returns name="bool">Boolean value</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.FamilyType">
            <summary>
            FamilyType methods for elements
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.FamilyType.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.FamilyType.All">
            <summary>
            Get all family types in current document
            </summary>
            <returns name="FamilyType">Family type</returns>
            <returns name="Category">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.FamilyType.ByCategory(System.Object)">
            <summary>
            Get all family types by category in list of documents
            </summary>
            <param name="category">Category as string or Category type</param>
            <returns name="FamilyType">Family type</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.FamilyType.FamilyDocument(System.Collections.IList)">
            <summary>
            open family document by family type
            </summary>
            <param name="familyType">Family type</param>
            <returns name="Document">Autodesk.Revit.DB.Document</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.FamilyType.HasAssociated(Revit.Elements.FamilyType)">
            <summary>
            Verify if family type has associated elements
            </summary>
            <param name="familyType">Family type</param>
            <returns name="bool">Boolean value</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.Floor">
            <summary>
            Floor methods for elements
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.Floor.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.Floor.SetAreaLoad(System.Collections.IList,System.Collections.IList,System.Collections.IList)">
            <summary>
            Set (structural) floor area load
            </summary>
            <param name="element">Element</param>
            <param name="areaLoadType">AreaLoadType</param>
            <param name="value">List of Load value</param>
            <returns name="value">Load value</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.SubCategory">
            <summary>
            Methods for selecting elements
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.SubCategory.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.SubCategory.Create(System.Object,System.String)">
            <summary>
            Create subcategory by category in document.
            </summary>
            <param name="category">Category</param>
            <param name="name">Name of the subcategory</param>
            <returns name="SubCategory">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SubCategory.Remove(System.Object,System.Object)">
            <summary>
            Remove subcategory by category in document.
            </summary>
            <param name="category">Category</param>
            <param name="subCategory">The subcategory as string or category</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SubCategory.ByCategory(System.Object)">
            <summary>
            Get subcategories by category in document
            </summary>
            <param name="category">Category</param>
            <returns name="SubCategory">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SubCategory.ByName(System.Object,System.String)">
            <summary>
             Get subcategory by name in document.
            </summary>
            <param name="category">Category</param>
            <param name="name">Name of the subcategory</param>
            <returns name="SubCategory">Category</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SubCategory.ByName(System.String)">
            <summary>
             Get subcategory by name in document.
            </summary>
            <param name="name">Name of the subcategory</param>
            <returns name="SubCategory">Category</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.SystemFamily">
            <summary>
            Methods for system families
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.CreateCompoundLayer(System.Collections.IList,System.Collections.Generic.List{System.Int32},System.Collections.Generic.List{Revit.Elements.Element},System.Collections.Generic.List{System.Double},System.Collections.Generic.List{System.Boolean},System.Collections.Generic.List{System.Boolean},System.Collections.Generic.List{System.Boolean},System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.Int32})">
            <summary>
            Create a layer by index at a specified compound layer in a system
            family type that have a compound structure (walls, floors, roofs etc.).
            </summary>
            <param name="elementType">The system family type</param>
            <param name="function">The function of the layer (integer)</param>
            <param name="material">The material (dynamo type)</param>
            <param name="thickness">Thickness of the layer</param>
            <param name="wrapping">Wrapping of the layer</param>
            <param name="variable">Set the layer variable</param>
            <param name="structural">Set the layer structural</param>
            <param name="placement">Placement of the layer (string)</param>
            <param name="index">The index of the layer</param>
            <returns name="ElementType">FamilyType</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.DeleteCompoundLayer(System.Collections.IList,System.Collections.Generic.List{System.Int32})">
            <summary>
            Delete a layer by index at a specified compound layer in a system
            family type that have a compound structure (walls, floors, roofs etc.).
            </summary>
            <param name="elementType">The system family type</param>
            <param name="index">The index of the layer</param>
            <returns name="ElementType">FamilyType</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.GetCompoundLayerMaterial(System.Collections.IList)">
            <summary>
            Get the compound layer material in a system family type that
            have a compound structure (walls, floors, roofs etc.).
            </summary>
            <param name="elementType">The system family type</param>
            <returns name="Material">Material</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.GetCompoundLayerWidth(System.Collections.IList)">
            <summary>
            Get the compound layer width in a system family type that
            have a compound structure (walls, floors, roofs etc.).
            </summary>
            <param name="elementType">The system family type</param>
            <returns name="double">Width</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.SetCompoundLayerMaterial(System.Collections.IList,System.Collections.Generic.List{Revit.Elements.Element},System.Collections.Generic.List{System.Int32})">
            <summary>
            Set the material by index at a specified compound layer in a system
            family type that have a compound structure (walls, floors, roofs etc.).
            </summary>
            <param name="elementType">The system family type</param>
            <param name="material">The material (dynamo type)</param>
            <param name="index">The index to set</param>
            <returns name="ElementType">FamilyType</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.SetCompoundLayerWidth(System.Collections.IList,System.Collections.Generic.List{System.Double},System.Collections.Generic.List{System.Int32})">
            <summary>
            Set the width by index at a specified compound layer in a system
            family type that have a compound structure (walls, floors, roofs etc.).
            </summary>
            <param name="elementType">The system family type</param>
            <param name="thickness">Thickness of the layer</param>
            <param name="index">The index to set</param>
            <returns name="ElementType">FamilyType</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.SetCompoundLayerWrapping(System.Collections.IList,System.Collections.Generic.List{System.Boolean},System.Collections.Generic.List{System.Int32})">
            <summary>
            Wrapping of the layer by index at a specified compound layer in a system
            family type that have a compound structure (walls, floors, roofs etc.).
            </summary>
            <param name="elementType">The system family type</param>
            <param name="wrapping">Wrapping of the layer</param>
            <param name="index">The index to set</param>
            <returns name="ElementType">FamilyType</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.SetCompoundLayerVariable(System.Collections.IList,System.Collections.Generic.List{System.Boolean},System.Collections.Generic.List{System.Int32})">
            <summary>
            Set the layer variable by index at a specified compound layer in a system
            family type that have a compound structure (walls, floors, roofs etc.).
            </summary>
            <param name="elementType">The system family type</param>
            <param name="variable">Set the layer variable</param>
            <param name="index">The index to set</param>
            <returns name="ElementType">FamilyType</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.SystemFamily.SetCompoundLayerStructural(System.Collections.IList,System.Collections.Generic.List{System.Boolean},System.Collections.Generic.List{System.Int32})">
            <summary>
            Set the layer structural by index at a specified compound layer in a system
            family type that have a compound structure (walls, floors, roofs etc.).
            </summary>
            <param name="elementType">The system family type</param>
            <param name="structural">Set the layer structural</param>
            <param name="index">The index to set</param>
            <returns name="ElementType">FamilyType</returns>
        </member>
        <member name="T:Orchid.Revit.Elements.Element">
            <summary>
            Methods for elements
            </summary>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.Elements.Element.IsFlipped(System.Collections.IList)">
            <summary>
            Get the element flip condition, output as boolean
            </summary>
            <param name="element">List of elements</param>
            <returns name="bool">List of booleans</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.IsHandFlipped(System.Collections.IList)">
            <summary>
            Get the element hand flip condition, output as boolean
            </summary>
            <param name="element">List of elements</param>
            <returns name="bool">List of booleans</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.IsFaceFlipped(System.Collections.IList)">
            <summary>
            Get the element face flip condition, output as boolean
            </summary>
            <param name="element">List of elements</param>
            <returns name="bool">List of booleans</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.Flipped(System.Collections.IList)">
            <summary>
            Get the element flip condition, output as element
            </summary>
            <param name="element">List of elements</param>
            <returns name="true">List of flipped elements</returns>
            <returns name="false">List of not flipped elements</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.HandFlipped(System.Collections.IList)">
            <summary>
            Get the element hand flip condition, output as element
            </summary>
            <param name="element">List of elements</param>
            <returns name="true">List of flipped elements</returns>
            <returns name="false">List of not flipped elements</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.FaceFlipped(System.Collections.IList)">
            <summary>
            Get the element face flip condition, output as element
            </summary>
            <param name="element">List of elements</param>
            <returns name="true">List of flipped elements</returns>
            <returns name="false">List of not flipped elements</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.Delete(System.Collections.IList)">
            <summary>
            Delete elements
            </summary>
            <param name="element">List of elements</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.Delete(System.Collections.Generic.IList{Autodesk.Revit.DB.Document},System.Collections.IList)">
            <summary>
            Delete elements
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <param name="element">List of elements</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.GetMaterial(System.Collections.IList)">
            <summary>
            Get material by element, return values in SI unit (m2/m3)
            </summary>
            <param name="element">List of element</param>
            <returns name="Material">List of material</returns>
            <returns name="area">List of area</returns>
            <returns name="volumne">List of volumne</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.SumByMaterial(System.Collections.IList)">
            <summary>
            Element by (summarized) material, return values in SI unit (m2/m3)
            </summary>
            <param name="material">List of material</param>
            <returns name="Element">List of element</returns>
            <returns name="area">List of area</returns>
            <returns name="volumne">List of volumne</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.SetType(System.Collections.IList,System.Collections.IList)">
            <summary>
            Set element by family type
            </summary>
            <param name="element">Element(s)</param>
            <param name="familyType">FamilyType(s)</param>
            <returns name="Element">Revit.Elements.Element</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.SetAnalyticalLocation(System.Collections.IList,System.String)">
            <summary>
            Set (structural) element analytical location
            </summary>
            <param name="element">Element(s)</param>
            <param name="location">Element analytical location</param>
            <returns name="Element">Analytical floor element</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.GetAnalytical(Revit.Elements.Element)">
            <summary>
            Get analytical element
            </summary>
            <param name="element">Revit.Elements.Element</param>
            <returns name="Element">Revit.Elements.Element</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.FamilyName(Revit.Elements.Element)">
            <summary>
            Get element family name
            </summary>
            <param name="element">Revit.Elements.Element</param>
            <returns name="string">Family name as string</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.ElementType(Autodesk.Revit.DB.Document,Revit.Elements.Element)">
            <summary>
            Returns the ElementType for this Element. Returns null if the Element cannot have a ElementType assigned.
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <param name="element">Revit.Elements.Element</param>
            <returns name="ElementType">Element Type or Null.</returns>
        </member>
        <member name="M:Orchid.Revit.Elements.Element.View(Revit.Elements.Element)">
            <summary>
            Get the view where the element is located
            </summary>
            <param name="element">Revit.Elements.Element</param>
            <returns name="View">View</returns>
        </member>
        <member name="T:Orchid.Revit.FamilyDocument.Document">
            <summary>
            Families methods for family documents
            </summary>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Document.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Document.LoadFamily(Autodesk.Revit.DB.Document)">
            <summary>
            Load family by file name, same core process as File.LoadFamily
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Document.AddLookupTable(Autodesk.Revit.DB.Document,System.String)">
            <summary>
            Load lookup file by name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="file">Lookup file (path) to load.</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Document.GetCategory(Autodesk.Revit.DB.Document)">
            <summary>
            Get the family document category.
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <returns name="Category">Category as Dynamo object</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Document.SetCategory(Autodesk.Revit.DB.Document,System.Object)">
            <summary>
            Set the family document category.
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="category">Gategory as string or Dynamo object</param>
            <returns name="Category">Category as Dynamo object</returns>
        </member>
        <member name="T:Orchid.Revit.FamilyDocument.Family">
            <summary>
            Families methods for families
            </summary>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Family.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Family.GetNested(Autodesk.Revit.DB.Document)">
            <summary>
            Get nested family in the familyDocument
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <returns name="Family">Family as Dynamo object</returns>
        </member>
        <member name="T:Orchid.Revit.FamilyDocument.FamilyType">
            <summary>
            Families methods for family types
            </summary>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.Current">
            <summary>
            Get the current family type
            </summary>
            <returns name="FamilyType">FamilyType as Revit object</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.Current(Autodesk.Revit.DB.Document)">
            <summary>
            Get the current family type in the familyDocument
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <returns name="FamilyType">FamilyType as Revit object</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.Name(Autodesk.Revit.DB.FamilyType)">
            <summary>
            Get the family type name
            </summary>
            <param name="familyType">The name of the family type</param>
            <returns name="string">Name as string</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.All">
            <summary>
            Get all family types
            </summary>
            <returns name="FamilyType">FamilyType as Revit object</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.All(Autodesk.Revit.DB.Document)">
            <summary>
            Get all family types in the familyDocument
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <returns name="FamilyType">FamilyType as Revit object</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.Create(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String})">
            <summary>
            Create family type by name. If no input to name is provided,
            then a default family type will be created named as the familyDocument.
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="name">The family type name</param>
            <returns name="FamilyType">FamilyType as Revit object</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.Rename(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.String})">
            <summary>
            Rename family type by name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="sourceName">The name of the source family type</param>
            <param name="targetName">The name of the target family type</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.Delete(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.Object})">
            <summary>
            Delete family type by name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="familyType">FamilyType as string or Revit object</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.FamilyType.GetNested(Autodesk.Revit.DB.Document)">
            <summary>
            Get nested family in the familyDocument
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <returns name="FamilyType">FamilyType as Dynamo object</returns>
        </member>
        <member name="T:Orchid.Revit.FamilyDocument.Formula">
            <summary>
            Families methods for formulas
            </summary>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Formula.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Formula.Get(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String})">
            <summary>
            Get family formula by parameter name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to get</param>
            <returns name="formula">Formula as string</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Formula.Set(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.String})">
            <summary>
            Set family formula by parameter name. Please notice a default type must exist!
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to set</param>
            <param name="value">The value</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Formula.Remove(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String})">
            <summary>
            Remove family formula value by name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to remove formula</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="T:Orchid.Revit.FamilyDocument.Nested">
            <summary>
            Families methods for parameters
            </summary>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Nested.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Nested.GetAssociated(Autodesk.Revit.DB.Document)">
            <summary>
            Get associated parameter, nested family, nested family type, and nested family parameter
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <returns name="documentParameter">Family document parameter</returns>
            <returns name="Family">Nested family in the document</returns>
            <returns name="FamilyType">Nested family type in the document</returns>
            <returns name="familyParameter">Nested family parameter in the document</returns>
        </member>
        <member name="T:Orchid.Revit.FamilyDocument.Parameter">
            <summary>
            Families methods for parameters
            </summary>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.#ctor">
            default private constructor --> hides the class in dynamo
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.Parameters(Autodesk.Revit.DB.Document)">
            <summary>
            Obtain all of the Parameters from the family document, sorted by Name.
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <returns name="Parameter">Parameter</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.Name(Autodesk.Revit.DB.FamilyParameter)">
            <summary>
            Get family parameter name
            </summary>
            <param name="parameter">FamilyParameter as Revit object</param>
            <returns name="string">Name as string</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.AddParameter(Autodesk.Revit.DB.Document,System.Collections.Generic.IList{System.String},System.String,System.String,System.String,System.Boolean,System.Boolean)">
            <summary>
            Add (create) parameter by name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to create</param>
            <param name="type">Parameter Type</param>
            <param name="group">Parameter Group</param>
            <param name="tooltip">Tooltip for the parameter</param>
            <param name="instance">Is instance parameter, otherwise it's a type parameter</param>
            <param name="reporting">Is reporting parameter. Is only available to Length and Angle parameters!</param>
            <returns name="Parameter">Parameter</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.AddParameter(Autodesk.Revit.DB.Document,System.Collections.Generic.IList{System.String},Revit.Elements.Category,System.String,System.String,System.Boolean,System.Boolean)">
            <summary>
            Add (create) parameter by name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to create</param>
            <param name="category">Category for Family Type as Parameter Type</param>
            <param name="group">Parameter Group</param>
            <param name="tooltip">Tooltip for the parameter</param>
            <param name="instance">Is instance parameter, otherwise it's a type parameter</param>
            <param name="reporting">Is reporting parameter. Is only available to Length and Angle parameters!</param>
            <returns name="Parameter">Parameter</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.AddSharedParameter(Autodesk.Revit.DB.Document,System.Collections.Generic.IList{System.String},System.String,System.String,System.String,System.String,System.Boolean,System.Boolean)">
            <summary>
            Add (create) shared parameter by name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to add</param>
            <param name="groupName">Group of the parameter for the shared parameter</param>
            <param name="type">Parameter Type</param>
            <param name="group">Parameter Group</param>
            <param name="tooltip">Tooltip for the parameter</param>
            <param name="instance">Is instance parameter, otherwise it's a type parameter</param>
            <param name="reporting">Is reporting parameter. Is only available to Length and Angle parameters!</param>
            <returns name="Parameter">Parameter</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.AddIfcParameters(Autodesk.Revit.DB.Document)">
            <summary>
            Add basic IFC parameters in the family (IfcExportAs, IfcExportType, IfcDescription, IFC CAD Layer)
            </summary>
            <param name="document">Autodesk.Revit.DB.Document</param>
            <returns name="Parameter">Parameter</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.GetValue(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.Object},System.Collections.Generic.List{System.String})">
            <summary>
            Get family parameter value by parameter name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="familyType">Family type as string or Revit object</param>
            <param name="parameterName">The name of the parameter to get</param>
            <returns name="valueByType">Value by familyType</returns>
            <returns name="valueByParameter">Value by parameterName</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.SetValue(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.Object},System.Collections.Generic.List{System.String},System.Collections.IList)">
            <summary>
            Set family parameter value by parameter name. Please notice a default type must exist!
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="familyType">Family type as string or Revit object</param>
            <param name="parameterName">The name of the parameter to set</param>
            <param name="value">The value to set</param>
            <returns name="Parameter">Parameter as Revit object</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.Rename(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String},System.Collections.Generic.List{System.String})">
            <summary>
            Rename family parameter by parameter name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="sourceName">The name of the source parameter</param>
            <param name="targetName">The name of the target parameter</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.Delete(Autodesk.Revit.DB.Document,System.Collections.Generic.IList{System.String})">
            <summary>
            Delete family parameter by parameter name
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to delete</param>
            <returns name="watch">Add a watch node to verify the output</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.Convert(Autodesk.Revit.DB.Document,System.Collections.Generic.IList{System.String},System.Boolean)">
            <summary>
            Convert shared parameter to family parameter
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to delete</param>
            <param name="instance">Is instance parameter, otherwise it's a type parameter</param>
            <returns name="Parameter">Parameter</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.IsReporting(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String})">
            <summary>
            Verify if parameter is a reporting parameter
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to verify</param>
            <returns name="bool">Boolean value</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.Associate(Autodesk.Revit.DB.Document,System.Collections.Generic.List{Revit.Elements.Element},System.Collections.IList,System.Collections.IList)">
            <summary>
            Associate document parameter with nested family parameter
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="familyType">Nested element (family type) in the familyDocument</param>
            <param name="documentParameter">The name of the familyDocument parameter to be associated</param>
            <param name="familyParameter">The name of the nested element parameter to be associated</param>
            <returns name="Parameter">Parameter</returns>
        </member>
        <member name="M:Orchid.Revit.FamilyDocument.Parameter.HasAssociated(Autodesk.Revit.DB.Document,System.Collections.Generic.List{System.String})">
            <summary>
            Verify if parameter has associated elements
            </summary>
            <param name="familyDocument">Family document as Revit document (rfa)</param>
            <param name="parameterName">The name of the parameter to verify</param>
            <returns name="bool">Boolean value</returns>
        </member>
    </members>
</doc>
